version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: minitest
    versions:
    - 5.14.3
    - 5.14.4
  - dependency-name: concurrent-ruby
    versions:
    - 1.1.8
  - dependency-name: simplecov
    versions:
    - 0.21.2
  - dependency-name: rake
    versions:
    - 13.0.3
